#!/bin/sh

#set -x
echo "## Welcome inside build scipt. ##"

modprobe loop
losetup -a
losetup -d /dev/loop*

#ARCHS="i586 x86_64"
#ARCHS="x86_64"
#ARCHS=i586
[ -z "$ARCHS" ] && ARCHS="$1"
[ -z "$ARCHS" ] && ARCHS=x86_64
[ -z "$TREE" ] && TREE="$2"
[ -z "$TREE" ] && TREE=cooker
[ -z "$VERSION" ] && VERSION="$3"
[ -z "$VERSION" ] && VERSION="2014.0"
[ -z "$RELEASE_ID" ] && RELEASE_ID="$4"
[ -z "$RELEASE_ID" ] && RELEASE_ID="alpha"
[ -z "$DESKTOP" ] && DESKTOP="$5"
[ -z "$DESKTOP" ] && DESKTOP=kde4
[ -z "$DISPLAYMANAGER" ] && DISPLAYMANAGER="$6"
[ -z "$DISPLAYMANAGER" ] && DISPLAYMANAGER=kdm

if [ "$RELEASE_ID" == "final" ]; then
    product_id="OpenMandriva.${VERSION}-$DESKTOP"
else
    if [[ "$RELEASE_ID" == "alpha" ]]; then
    	RELEASE_ID="$RELEASE_ID.`date +%Y%m%d`"
    fi
    product_id="OpenMandriva.${VERSION}-${RELEASE_ID}-$DESKTOP"
fi

echo "## Current product build is $ARCHS $TREE $VERSION $RELEASE_ID $DESKTOP##"

REPOURL="http://abf-downloads.abf.io/$TREE/repository/#ARCH#"
TZ="Universal"
SVCEN="acpid,alsa,atd,avahi-daemon,irqbalance,netfs,network,network-up,partmon,resolvconf,rpcbind,sound,udev-post,mandrake_everytime,crond"
SVCDIS="sshd,pptp,pppoe,ntpd,iptables,ip6tables,shorewall,nfs-server,mysqld,abrtd,mysql,postfix,cups"

PKGLISTFILE=iso-pkg-lists/omdv-$DESKTOP.lst

DIRNAME=$(dirname $0)
cd $DIRNAME

build_root="./"
d=`date +%Y.%m.%d-%H.%M`
echo "$i.$d" > ${build_root}/version.txt

product_name_file="${build_root}/.name.txt" ; touch ${product_name_file}

counter="${build_root}/.counter"
touch ${counter}
i=`cat ${counter}`
i=`expr $i + 1`
echo $i > ${counter}

ks="${build_root}/.ks"

# build different architectures
export DURING_INSTALL=true
for arch in $ARCHS; do
	cp -f ks.template ${ks}
	sed -i -e "s|#REPOURL#|${REPOURL}|g" ${ks}
	sed -i -e "s|#ARCH#|${arch}|g" ${ks}
	sed -i -e "s|#TREE#|${TREE}|g" ${ks}
	sed -i -e "s|#TZ#|${TZ}|g" ${ks}
	sed -i -e "s|#SVCEN#|${SVCEN}|g" ${ks}
	sed -i -e "s|#SVCDIS#|${SVCDIS}|g" ${ks}
	sed -i -e "s|#PKGLISTFILE#|${PKGLISTFILE}|g" ${ks}
	sed -i -e "s|#DISPLAYMANAGER#|${DISPLAYMANAGER}|g" ${ks}
	sed -i -e "s|#DESKTOP#|${DESKTOP}|g" ${ks}

	mkdir -p $build_root/${product_id}/
	LABEL=${product_id}.$arch
	[ `echo $LABEL |wc -m` -gt 32 ] && LABEL="OpenMandriva_${VERSION}"

	echo "## Starting livecd-creator tool. ##"

	livecd-creator -d -v --config=${ks} --fslabel=$LABEL
    
	echo "## End of livecd-creator procedure##"
    
	[ "$LABEL" != "${product_id}.$arch" ] && mv $LABEL.iso ${product_id}.$arch.iso
	mv ${product_id}.$arch.iso $build_root/${product_id}/
	cd $build_root/${product_id}/
	md5sum  ${product_id}.$arch.iso > ${product_id}.$arch.iso.md5sum
	sha1sum ${product_id}.$arch.iso > ${product_id}.$arch.iso.sha1sum

	echo "## ALL DONE! $build_root/${product_id}/${product_id}.$arch.iso ##"
done
unset DURING_INSTALL
