#!/bin/bash

OURDIR=$(realpath $(dirname $0))
if echo $OURDIR |grep -q /home/vagrant; then
	# We're in ABF -- things are a little odd
	BLDNAME=iso-build-tools
else
	BLDNAME=$(basename $OURDIR)
fi

if pwd |grep -q "^$OURDIR"; then
	echo "Don't run this script from within its directory."
	echo "Try:"
	echo "cd $(realpath $OURDIR/..) ; $BLDNAME/$(basename $0)"
	exit 1
fi

if [ "`id -u`" != "0" ]; then
	# We need to be root for umount and friends to work...
	exec sudo $0 "$@"
	echo Run me as root
	exit 1
fi

[ -z "$EXTARCH" ] && EXTARCH="$1"
[ -z "$EXTARCH" ] && EXTARCH="x86_64"
CHROOTNAME="buildchroot-$EXTARCH"

[ -z "$TREE" ] && TREE="$2"
[ -z "$TREE" ] && TREE=cooker

[ -z "$RELEASE_ID" ] && RELEASE_ID="$3"
[ -z "$RELEASE_ID" ] && RELEASE_ID="alpha.`date +%Y%m%d`"

[ -z "$VERSION" ] && VERSION="$4"
[ -z "$VERSION" ] && VERSION="`date +%Y.0`"

REPOPATH="http://abf-downloads.rosalinux.ru/$TREE/repository/$EXTARCH/"
SRCPATH="https://abf.rosalinux.ru/openmandriva/$BLDNAME.git"
PKGLIST="https://abf.rosalinux.ru/openmandriva/iso-pkg-lists.git"
LOGDIR="."
BRANCH="master"
CHROOTOPTS="$CHROOTNAME /bin/su root -c"

umount_all() {
	umount -Rf $CHROOTNAME/sys || :
	umount -Rf $CHROOTNAME/proc || :
	umount -Rf $CHROOTNAME/dev/pts || :
	umount -Rf $CHROOTNAME/dev || :
}
error() {
	umount_all
	exit 1
}

# Don't leave potentially dangerous stuff if we had to error out...
trap error ERR

pushd "$OURDIR"
[ -d iso-pkg-lists ] || git clone -b $BRANCH $PKGLIST
popd

echo $CHROOTNAME
echo $REPOPATH
echo $EXTARCH
if [ -d "$CHROOTNAME" ]; then
	echo "## Chroot $CHROOTNAME exists. Using existing chroot. ##"
	urpmi.update --urpmi-root $CHROOTNAME main
	umount_all
else
	echo "## Chroot $CHROOTNAME is missing. Creating chroot. ##"
	mkdir $CHROOTNAME
	urpmi.addmedia --urpmi-root $CHROOTNAME --distrib --all-media $REPOPATH > $LOGDIR/addrepo.log 2>&1
	urpmi.update --urpmi-root $CHROOTNAME main
	urpmi --no-suggests --no-verify-rpm --debug --verbose --urpmi-root $CHROOTNAME --root $CHROOTNAME basesystem-minimal basesystem urpmi rpm locales-en rpm-build livecd-tools syslinux yum lorax grub-efi grub-efi-efi git --prefer /default-kde4-config/ --prefer /distro-theme-OpenMandriva/ --auto
	mkdir -p $CHROOTNAME/dev
	mkdir -p $CHROOTNAME/dev/pts
	mkdir -p $CHROOTNAME/proc
	mkdir -p $CHROOTNAME/sys
fi

### these need to be mounted for anything to work inside the chroot
mount --bind /dev/	$CHROOTNAME/dev
mount --bind /dev/pts	$CHROOTNAME/dev/pts
mount --bind /proc	$CHROOTNAME/proc
mount --bind /sys	$CHROOTNAME/sys
cp /etc/resolv.conf	$CHROOTNAME/etc/

echo "## Making sure we have the latest from $BLDNAME. ##"

# For now, unconditionally overwrite the $BLDNAME instance inside the chroot
# so any local changes are sure to get in
# May want to remove the rm -rf line below once things have stabilized.
rm -rf "$CHROOTNAME/$BLDNAME"

if [ ! -d "$CHROOTNAME/$BLDNAME" ]; then
	if [ -d "`dirname $0`"/.git ]; then
		# If possible, copy the running instance to save some network traffic
		cp -a `dirname $0` $CHROOTNAME/$BLDNAME
		chroot $CHROOTOPTS "cd /$BLDNAME; git pull"
	else
		chroot $CHROOTOPTS "cd / && git clone -b $BRANCH $SRCPATH"
		chroot $CHROOTOPTS "cd /$BLDNAME; git clone -b $BRANCH $PKGLIST"
	fi
fi

echo "## Beginning ISO creation. ##"
set -x
chroot $CHROOTOPTS "sh -x /$BLDNAME/build $EXTARCH $TREE $VERSION $RELEASE_ID" 2>&1 |tee $LOGDIR/build.log

mv $CHROOTNAME/$BLDNAME/*/*.iso* $LOGDIR/
ls -l $LOGDIR/*.iso*

if echo $OURDIR |grep -q /home/vagrant; then
	# We're running in ABF -- adjust to its directory structure
	mkdir -p /home/vagrant/results /home/vagrant/archives
	mv $LOGDIR/*.iso* /home/vagrant/results/
	mv $LOGDIR/*.log /home/vagrant/archives/
fi

umount_all
